import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { rollup } from 'rollup';

const root = new URL('../', import.meta.url);
const output = new URL('dist-editor/water-scripts.mjs', root);
await mkdir(fileURLToPath(new URL('dist-editor/', root)), { recursive: true });
const bundle = await rollup({
    input: fileURLToPath(new URL('src/scripts/index.js', root)),
    external: ['playcanvas'],
    treeshake: false
});
try {
    const generated = await bundle.generate({
        format: 'es',
        banner: '// Water + atmosphere PlayCanvas Editor components. Generated by npm run build:editor.\n// Import only this file into the Editor; playcanvas is supplied by the Editor runtime.'
    });
    let code = generated.output[0].code;
    // Keep the exact exported-class form understood by the Editor's attribute parser.
    for (const name of ['WaterScript', 'SkyScript']) {
        const declaration = `class ${name} extends Script`;
        if (!code.includes(declaration)) throw new Error(`Editor bundle is missing ${name}`);
        code = code.replace(declaration, `export ${declaration}`);
    }
    code = code.replace(/^export \{ SkyScript, WaterScript \};\n/m, '');
    await writeFile(output, code);

} finally { await bundle.close(); }
console.log(`Editor script: ${fileURLToPath(output)}`);
